<?xml version="1.0" encoding="utf-8"?><Database Name="A_Zawodnicy" Class="ModelBazyDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=A_Zawodnicy;User ID=sa" SettingsObjectName="P02AplikacjaZawodnicy.Properties.Settings" SettingsPropertyName="A_ZawodnicyConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.zawodnicy" Member="ZawodnikDB">
    <Type Name="ZawodnikDB">
      <Column Name="id_zawodnika" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_trenera" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="imie" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="nazwisko" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="kraj" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="data_ur" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="wzrost" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="waga" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>